### ISSUE TITLE
Error in requires

### ISSUE THREAD

**Issue by blazingkin** [blazingkin/blz-ospl#25]
Not sure what this is, figure it out later

```
java.lang.NullPointerException
        at com.blazingkin.interpreter.executor.sourcestructures.Process.handleImports(Process.java:202)
        at in.blazingk.blz.packagemanager.FileImportManager.importFile(FileImportManager.java:23)
        at com.blazingkin.interpreter.executor.Executor.run(Executor.java:67)
        at com.blazingkin.interpreter.Interpreter.runExecutor(Interpreter.java:138)
        at com.blazingkin.interpreter.Interpreter.run(Interpreter.java:105)
        at com.blazingkin.interpreter.Interpreter.main(Interpreter.java:32)
```

can be replicated with a single file that has
```
require file
:main

end
```

**Comment by blazingkin** [comment]
Fixed. This was a problem with relative paths and Java's getParentFile method returning null.

I fixed this by converting all relative paths to absolute ones before using the getParentFile method.
