### ISSUE TITLE
L-Values of multiple array/hash lookups are broken

### ISSUE THREAD

**Issue by blazingkin** [blazingkin/blz-ospl#29]
The L-Value is not correctly calculated when more than one square bracket operator is used.

Example
```
arr = [[1],[2]]
arr[0][0] = 3
```

This currently causes a NullPointerException
```
java.lang.NullPointerException
        at com.blazingkin.interpreter.variables.Variable.isDouble(Variable.java:284)
        at com.blazingkin.interpreter.variables.Variable.getValue(Variable.java:215)
        at com.blazingkin.interpreter.variables.Variable.typeOf(Variable.java:591)
        at com.blazingkin.interpreter.executor.astnodes.AssignmentNode.execute(AssignmentNode.java:35)
        at com.blazingkin.interpreter.executor.sourcestructures.RegisteredLine.run(RegisteredLine.java:56)
        at com.blazingkin.interpreter.executor.astnodes.BlockNode.execute(BlockNode.java:84)
        at com.blazingkin.interpreter.repl.REPL.immediateModeLoop(REPL.java:100)
        at com.blazingkin.interpreter.Interpreter.selectOption(Interpreter.java:68)
        at com.blazingkin.interpreter.Interpreter.run(Interpreter.java:93)
        at com.blazingkin.interpreter.Interpreter.main(Interpreter.java:31)
```

**Comment by blazingkin** [comment]
Looks like this was fixed at some point
